# YOU don't need this on codeocean
# This is for conda env building only
name: swdb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyter
  - jupyterlab
  - pip:
    - aind-behavior-gym==0.4.3
    - matplotlib==3.9.4
    - numpy==2.0.2
    - pandas==2.3.1
    - pydantic==2.11.7
    - scipy==1.13.1
